insert into exercicios set
    titulo='Exercicio teste 1',
    descricao='Maecenas varius, lorem ac elementum faucibus, diam diam tincidunt purus, ut semper felis sem et massa. Phasellus rutrum, nibh ac pretium eleifend, enim ante porta odio, in porttitor eros erat et neque. Aenean nibh est, tempor a diam vel, sodales varius nibh. Proin ut sagittis est, sit amet vestibulum tortor. Nulla vel posuere metus. Etiam mattis, ex tincidunt tincidunt fringilla, tellus enim fringilla arcu, vel imperdiet orci eros eu neque. Donec congue sem ac eleifend consequat. Integer elit ligula, tempor a iaculis ac, dictum id orci. Donec euismod condimentum luctus. Nullam eleifend massa arcu, nec condimentum elit vehicula ut. Sed lacinia, velit sed posuere consequat, turpis nulla auctor tortor, eu vulputate eros orci ac enim. Sed faucibus massa vel quam eleifend, et varius tortor luctus. Proin porttitor lacus ligula, eu porta neque finibus nec. Ut vitae mauris in magna blandit eleifend a ut arcu. ',
    foto='',
    id_professor = 2;
insert into exercicios set
    titulo='Exercicio teste 2',
    descricao='Maecenas varius, lorem ac elementum faucibus, diam diam tincidunt purus, ut semper felis sem et massa. Phasellus rutrum, nibh ac pretium eleifend, enim ante porta odio, in porttitor eros erat et neque. Aenean nibh est, tempor a diam vel, sodales varius nibh. Proin ut sagittis est, sit amet vestibulum tortor. Nulla vel posuere metus. Etiam mattis, ex tincidunt tincidunt fringilla, tellus enim fringilla arcu, vel imperdiet orci eros eu neque. Donec congue sem ac eleifend consequat. Integer elit ligula, tempor a iaculis ac, dictum id orci. Donec euismod condimentum luctus. Nullam eleifend massa arcu, nec condimentum elit vehicula ut. Sed lacinia, velit sed posuere consequat, turpis nulla auctor tortor, eu vulputate eros orci ac enim. Sed faucibus massa vel quam eleifend, et varius tortor luctus. Proin porttitor lacus ligula, eu porta neque finibus nec. Ut vitae mauris in magna blandit eleifend a ut arcu. ',
    foto='',
    id_professor = 2;
insert into exercicios set
    titulo='Exercicio teste 3',
    descricao='Maecenas varius, lorem ac elementum faucibus, diam diam tincidunt purus, ut semper felis sem et massa. Phasellus rutrum, nibh ac pretium eleifend, enim ante porta odio, in porttitor eros erat et neque. Aenean nibh est, tempor a diam vel, sodales varius nibh. Proin ut sagittis est, sit amet vestibulum tortor. Nulla vel posuere metus. Etiam mattis, ex tincidunt tincidunt fringilla, tellus enim fringilla arcu, vel imperdiet orci eros eu neque. Donec congue sem ac eleifend consequat. Integer elit ligula, tempor a iaculis ac, dictum id orci. Donec euismod condimentum luctus. Nullam eleifend massa arcu, nec condimentum elit vehicula ut. Sed lacinia, velit sed posuere consequat, turpis nulla auctor tortor, eu vulputate eros orci ac enim. Sed faucibus massa vel quam eleifend, et varius tortor luctus. Proin porttitor lacus ligula, eu porta neque finibus nec. Ut vitae mauris in magna blandit eleifend a ut arcu. ',
    foto='',
    id_professor = 2;
